name: Ejecutar pipeline de datos

on:
  push:
    branches: [ main ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      BUCKET_NAME: mi-bucket-ejemplo2025
      AWS_REGION: us-east-1

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
    

      - name: Ejecutar script
        run: |
          set -e
          mkdir -p logs
          python script.py | tee logs/output.log

      - name: Guardar logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/output.log
